---
# x86_64
# aarch64

- name: Create directory for castopod
  ansible.builtin.file:
    dest: /opt/castopod/
    mode: 0744
    owner: root
    state: directory

- name: Generate docker-compose file for castopod
  ansible.builtin.template:
    dest: /opt/castopod/docker-compose.yml
    mode: 0644
    owner: root
    validate: docker-compose -f %s pull
    src: castopod/docker-compose.yml.j2

- name: Deploy castopod
  community.docker.docker_compose:
    project_src: /opt/castopod
    remove_orphans: true
    state: present
- name: Fix owner of folder
  ansible.builtin.file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.owner }}"
    recurse: true
  loop:
    - dest: /opt/castopod/castopod-media
      owner: 33
    - dest: /opt/castopod/castopod-cache
      owner: 999
    - dest: /opt/castopod/castopod-db
      owner: 999
