---
# x86_64
# aarch64

- name: Create directory for yopass
  ansible.builtin.file:
    dest: /opt/yopass/
    mode: 0744
    owner: root
    state: directory

- name: Generate docker-compose file for yopass
  ansible.builtin.copy:
    dest: /opt/yopass/docker-compose.yml
    mode: 0644
    owner: root
    validate: docker-compose -f %s pull
    content: |
      ---
      networks:
        traefik_default:
          external: true
        yopass:
      services:
        app:
          image: "jhaals/yopass:{{ deploy_yacht_version }}"
          labels:
            com.centurylinklabs.watchtower.enable: "true"
            traefik.docker.network: traefik_default
            traefik.enable: true
            traefik.http.routers.yopass.entrypoints: websecure
            traefik.http.routers.yopass.rule: Host(`{{ deploy_yopass_hostname }}`)
            traefik.http.routers.yopass.service: yopass
            traefik.http.routers.yopass.tls: true
            traefik.http.routers.yopass.tls.certresolver: le
            traefik.http.services.yopass.loadbalancer.server.port: 80
          command: "--memcached=memcached:11211 --port 80"
          logging:
            driver: "json-file"
            options:
              max-file: "3"
              max-size: "1m"
          networks:
            - traefik_default
            - yopass
        memcached:
          image: memcached
          restart: always
          labels:
            com.centurylinklabs.watchtower.enable: "true"
          logging:
            driver: "json-file"
            options:
              max-file: "3"
              max-size: "1m"
          networks:
            - yopass
      version: "3"
- name: Deploy yopass
  community.docker.docker_compose:
    project_src: /opt/yopass
    remove_orphans: true
    state: present
