---

- name: Update hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Update hostname in hosts localhost
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 localhost"
    regexp: "^127.0.0.1"
    state: present

- name: Update hostname in hosts
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname_short }}"
    regexp: "^127.0.1.1 "
    state: present
