---

- name: Update repositories
  ansible.builtin.apt:
    update_cache: true
  when: ansible_facts['os_family'] == 'Debian'
  changed_when: false

- name: Install packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop: "{{ packages_to_install }}"
